### ISSUE TITLE
Adding older WMT test sets

### ISSUE THREAD

**Issue by alvations** [Helsinki-NLP/OPUS-MT-testsets#1]
@jorgtied not sure if this helps: https://github.com/alvations/warmth =)

It includes the previous years hypotheses submissions on top of the references

**Comment by jorgtied** [comment]
Thanks - I'll have a look. The purpose in this repo is to collect as many benchmarks as possible to support some kind of flexible leaderboard for MT that we want to include for OPUS-MT models and others ...

**Comment by jorgtied** [comment]
done
